### ISSUE TITLE
Many general exceptions

### ISSUE THREAD

**Issue by michalsustr** [flashpixx/Light-Jason#59]
There are many places in the code that throw too general exceptions, for example `IBaseAgentGenerator` throws an `Exception` in the constructor. These should be better named, maybe with some exception hierarchy (eg `LJException` -> `ParsingException` -> `InvalidCharacterException` or something like that)

**Comment by flashpixx** [comment]
We are using for exceptions specified exception e.g. runtime errors contains agent and execution context https://github.com/LightJason/AgentSpeak/tree/master/src/main/java/org/lightjason/agentspeak/error

But the general exceptions are not encapsulated by LJ itself, e.g. the AntLR exceptions are passed.
So in my opinion we should encapsulate any kind of exception in such a hierarchy. I will took this as an enhancement
