### ISSUE TITLE
Add shortcut methods for triggers

### ISSUE THREAD

**Issue by michalsustr** [flashpixx/Light-Jason#60]
I see a lot of examples have code like 

`this.trigger( CTrigger.from( ITrigger.EType.ADDGOAL, CLiteral.from( "vehicle/collision" ) ) );`

Can it be simplified to something like

`this.addGoal("vehicle/collision");`

(eg add new method to `IBaseAgent`)

**Comment by flashpixx** [comment]
With your proposal I'm mixing agent execution with trigger data, because I must implement for each enum typ in ```EType``` a method, so if I extend the enum, I must also extend the agent methods. 
That is not possible, but I think I can add a method ```build( ILiteral p_literal )``` to the enum type, so that the ```CTrigger.from``` can be removed

**Comment by flashpixx** [comment]
fixed for the next release
